name: vibemon_mobile
description: VibeMon - Мониторинг вибрации и температуры оборудования

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_blue_plus: ^1.31.0
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
